name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deploy to Shopify
        run: |
          # Install the Shopify CLI if not already installed
          npm install -g @shopify/cli

          # Authenticate with Shopify using your API key and password

          shopify theme deploy --password ${{ secrets.SHOPIFY_PASSWORD }} --store ${{ secrets.SHOPIFY_STORE_URL }} --apikey ${{ secrets.SHOPIFY_API_KEY }}

          # Set the Shopify store URL
          # shopify target add ${{ secrets.SHOPIFY_STORE_URL }}

          # Deploy your theme
          # shopify theme deploy 
          
        env:
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
